bigquery:
  target: dbt_x_airflow

  outputs:
  
    dbt_x_airflow:
      type: bigquery
      method: service-account
      project: ${GBQ_PROJECT}
      dataset: ${GBQ_DATASET}
      threads: 5
      keyfile: "{{ env_var('DBT_HOME') }}/keyfile.json"
      timeout_seconds: 300
      priority: interactive
      retries: 1

    
