version: 2

sources:
  - name: jaffle_shop
    project: dbt-tutorial
    dataset: jaffle_shop
    tables:
      - name: customers
        description: "put your table desciption here"
        columns:
          - name: id
            tests:
              - unique
              - not_null
      
      - name: orders
        description: "put your table desciption here"
        loaded_at_field: _etl_loaded_at
        freshness: 
            warn_after: {count: 12 , period: hour}
            error_after: {count: 24 , period: hour}
        columns:
          - name: id
            tests:
              - unique              
              - not_null

  - name: stripe
    project: dbt-tutorial
    dataset: stripe
    tables:
      - name: payment

models:
  - name: stg_customers
    description: "staging customer table"
    columns:
      - name: customer_id
        description: "customer's id"
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns: 
      - name: order_id
        tests:
          - unique
          - not_null

      - name: status
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - return_pending
                - placed